### ISSUE TITLE
Line ending handling with sort functions

### ISSUE THREAD

**Issue by Ste1io** [carlocardella/vscode-TextToolbox#26] opened 2023-01-09 03:20 UTC
When inverting a selection of lines that that were selected by line (vs by character), the final line break at the end of the selection is included in the sorting, resulting in an unintended line break at the top of the selection, with the first unselected line following the sorted region being concatenated onto the last sorted line. Sorting options exhibit the same behavior, but without the blank line at the top.

I know that was a mouthful, so hopefully hopefully the gifs below make more sense. EOL sequence for the file is `CRLF`.

How to repro the issue (shows both sorting and invert behavior):

![Code_NhOryjIUvU](https://user-images.githubusercontent.com/37424493/211235551-0657e6c7-c245-40ef-b76b-df18e09d31b1.gif)

Expected behavior would be identical to when selecting by character, as supposed to by line:

![Code_f4YqGZ90UY](https://user-images.githubusercontent.com/37424493/211235627-4c67b771-271d-4bdb-89df-fc6946c689a0.gif)

**Comment by carlocardella** [comment] 2023-01-09 03:25
Thanks for reporting this, the gifs do help. 
I have an idea on the cause, I'll see if I can fix it tomorrow

**Comment by Ste1io** [comment] 2023-01-09 03:37
Excluding from the sort operation any empty line that contains only an EOL sequence and is the last line in the selection, coupled with decreasing the selected line count by 1 would fix it I'd imagine. The invert option is already filtering out the empty line, it just needs the line count adjusted to not include it also.

**Comment by Ste1io** [comment] 2023-01-09 07:05
Just a quick observation for what it's worth:

Single-line selections, and multi-line selections made by dragging up (resulting in the EOL capture at the top, instead of the bottom) emit the same behavior. (Technically, a whole-line selection made on a single line would count as two lines anyways even if perceived as a single line, but worth noting nonetheless.)

![Code_HTxxLdWLhh](https://user-images.githubusercontent.com/37424493/211253604-a547707c-619e-45ff-847e-0ac33281948c.gif)

**Comment by carlocardella** [comment] 2023-01-10 04:10
![tt sort selection](https://user-images.githubusercontent.com/5784415/211460007-744155ef-c074-430a-b13b-2449d7c28d69.gif)

**Comment by carlocardella** [comment] 2023-01-10 04:36
Released with [2.10.2](https://github.com/carlocardella/vscode-TextToolbox/tree/v2.10.2) (pre-release version), it should be available in the Marketplace shortly

**Comment by carlocardella** [comment] 2023-01-10 16:12
> Just a quick observation for what it's worth:
> 
> Single-line selections, and multi-line selections made by dragging up (resulting in the EOL capture at the top, instead of the bottom) emit the same behavior. (Technically, a whole-line selection made on a single line would count as two lines anyways even if perceived as a single line, but worth noting nonetheless.)

e906199544adecfdafcf96d7b832821ae7eccd7e

**Comment by Ste1io** [comment] 2023-01-10 22:11
Testing prerelease v2.10.3:

Line-selections are still including the orphan EOL in the sort, producing unexpected results. Note that "Line-selections" are referring to a full-line selection, made by clicking on the line number to the left. Notice how moving lines up and down using Alt with an up/down arrow exclude the line where the cursor appears below the selection. The sort option should do likewise.

![](https://i.imgur.com/72JZiok.gif)

**Comment by carlocardella** [comment] 2023-01-10 22:42
Ok, for the first gif the problem is the cursor at the beginning on the new file (but without characters selected): the current logic uses the cursor's position to determine if the line should be sorted or not, regardless of an actual selection. I'll change that.

The secont gif is more surprising, line 13 (`zz1`) should not be touched at all... 🤔

**Comment by Ste1io** [comment] 2023-01-10 23:00
The cursor position is important for placing it correctly after the sort operation, but it's of no relevancy to what gets sorted. In the first gif, it has to go on the next line since the line-selections include the EOL with the lsat line (seen by the extra non-existent space at the end of each highlighted line). Doing a normal char selection (click-drag the actual text, not the line numbers) will omit the final line's EOL in the selection because your selection area (which the cursor follows) stops *on* that last line (before EOL) not *below* it (after EOL).

Note that the cursor position is different after the sort, in the first gif, and in the second gif it is correct but the last line no longer shows the EOL as part of the selection.

**Comment by carlocardella** [comment] 2023-01-12 02:00
586343f7a8c2126a5b4a2d80a3ffcf618e56a5b3

Pre-release `2.10.4` should be available in the Marketplace shortly

**Comment by Ste1io** [comment] 2023-01-12 23:57
💯 works perfectly

**Closed** 2023-01-13 01:20 UTC
Labels: bug, needs validation, pre-release, ready for release
